version: '{branch}-{build}'

environment:
  SOURCEMOD_VERSION: 1.9-dev

install:
  - '"%VS120COMNTOOLS%vsvars32.bat"'
  - git clone https://github.com/alliedmodders/sourcemod.git -b %SOURCEMOD_VERSION% --depth 1 --recursive %APPVEYOR_BUILD_FOLDER%\..\sourcemod
  - git clone https://github.com/alliedmodders/ambuild.git --depth 1 %APPVEYOR_BUILD_FOLDER%\..\ambuild
  - move $APPVEYOR_BUILD_FOLDER\taglib $TRAVIS_BUILD_DIR\_taglib
  - git clone https://github.com/taglib/taglib.git --depth 1 $APPVEYOR_BUILD_FOLDER\taglib
  - move $APPVEYOR_BUILD_FOLDER\_taglib\taglib\AMBuilder $APPVEYOR_BUILD_FOLDER\taglib\taglib\AMBuilder && type NUL > $APPVEYOR_BUILD_FOLDER\taglib\taglib\taglib_config.h
  - cd %APPVEYOR_BUILD_FOLDER%\..\ambuild && python setup.py build && python setup.py install

build_script:
  - mkdir %APPVEYOR_BUILD_FOLDER%\build && cd %APPVEYOR_BUILD_FOLDER%\build
  - python ..\configure.py --enable-optimize
  - C:\Python27\Scripts\ambuild
